version: "3.7"
services:
    server-dev:
        image: jboss7sivemtx:latest
        ports:
            - "8089:8080"
            - "9090:9090"
            - "9990:9990"
            - "9999:9999"
            - "8787:8787"
        volumes:
            - server-target:/opt/jboss-eap-7.0/standalone/deployments/
            - /var/run/docker.sock:/var/run/docker.sock
    dev:
        image: asesoftware.azurecr.io/billetera_web_dev:latest
        tty: true
        stdin_open: true
        entrypoint:
            - bash
        volumes:
            - source-files:/usr/mysources/
            - mavenm2:/root/.m2/
            - server-target:/usr/target
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    source-files:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${my_sources_path}
    mavenm2:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${maven_m2_path}
    server-target:
        driver_opts:
            type: none
            o: bind
            device: ${target_path}
    
